/**
 * Shape of `src/data/model_report.json`, generated by `python -m src.export_report`.
 * Every field traces back to a persisted artifact in models/ or to a re-scoring of
 * the held-out split through the same ONNX path the API serves with.
 */

export type DatasetKey = 'internal' | 'external'

export interface Confusion {
  readonly tp: number
  readonly fp: number
  readonly tn: number
  readonly fn: number
}

export interface RocPoint {
  readonly fpr: number
  readonly tpr: number
}

export interface PrPoint {
  readonly recall: number
  readonly precision: number
}

/** One operating point of the threshold sweep — real counts, not interpolation. */
export interface SweepPoint extends Confusion {
  readonly t: number
  readonly sensitivity: number
  readonly specificity: number
  readonly precision: number
  readonly accuracy: number
}

export interface DatasetResult {
  readonly n: number
  readonly positives: number
  readonly prevalence: number
  readonly roc_auc: number
  readonly pr_auc: number
  readonly confusion: Confusion
  readonly sensitivity: number
  readonly specificity: number
  readonly precision: number
  readonly accuracy: number
  readonly roc: readonly RocPoint[]
  readonly pr: readonly PrPoint[]
  readonly sweep: readonly SweepPoint[]
}

export interface DatasetMeta {
  readonly label: string
  readonly source: string
  readonly note: string
}

export interface CalibrationBin {
  readonly confidence: number
  readonly empirical: number
}

export interface ModelReport {
  readonly generated_at: string
  readonly model_version: string
  readonly probability_scale: string
  readonly threshold: {
    readonly raw: number
    readonly calibrated: number
    readonly target_sensitivity: number
    readonly chosen_on: string
    readonly val_sensitivity: number
    readonly val_specificity: number
  }
  readonly temperature: {
    readonly value: number
    readonly fit_on: string
    readonly selection: string
  }
  readonly datasets: Record<DatasetKey, DatasetMeta>
  readonly internal: DatasetResult
  readonly external: DatasetResult
  readonly calibration: {
    readonly temperature: number
    readonly ece_raw: number
    readonly ece_scaled: number
    readonly bins_raw: readonly CalibrationBin[]
    readonly bins_scaled: readonly CalibrationBin[]
    readonly n_bins: number
  }
  readonly triage: {
    readonly band: readonly number[]
    readonly threshold_calibrated: number
    readonly target_accuracy: number
    readonly coverage: number
    readonly decided_accuracy: number
    readonly full_accuracy: number
    readonly zones: {
      readonly routine: number
      readonly uncertain: number
      readonly urgent: number
      readonly uncertain_true_pneumonia: number
    }
    readonly curve: readonly { readonly coverage: number; readonly accuracy: number }[]
  }
  readonly fairness: {
    readonly flag_floor: number
    readonly overall_sensitivity: number
    readonly by_subgroup: readonly {
      readonly dimension: string
      readonly subgroup: string
      readonly n_pos: number
      readonly sensitivity: number
      readonly flag: boolean
    }[]
    readonly by_negative_class: readonly {
      readonly neg_class: string
      readonly n_neg: number
      readonly specificity: number
    }[]
  }
}
